AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HackOverflow Backend API

Parameters:
  DatabaseURL:
    Type: String
    Description: Database connection URL
    NoEcho: true
  SecretKey:
    Type: String
    Description: JWT secret key
    NoEcho: true
  FrontendURL:
    Type: String
    Description: Frontend URL for CORS
    Default: "https://hackoverflow.srkrcodingclub.in"
  CloudinaryCloudName:
    Type: String
    Description: Cloudinary Cloud Name
  CloudinaryAPIKey:
    Type: String
    Description: Cloudinary API Key
    NoEcho: true
  CloudinaryAPISecret:
    Type: String
    Description: Cloudinary API Secret
    NoEcho: true

Resources:
  # REST API Gateway with explicit stage configuration
  HackOverflowRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: !Sub "'${FrontendURL}'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token,Accept,Accept-Encoding,Accept-Language,Cache-Control,Connection,Host,Origin,Pragma,Referer,User-Agent,X-Requested-With'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowCredentials: true
      BinaryMediaTypes:
        - "multipart/form-data"
        - "image/*"
        - "application/octet-stream"

  HackOverflowAPI:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures: [x86_64]
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          NODE_ENV: production
          DATABASE_URL: !Ref DatabaseURL
          SECRET_KEY: !Ref SecretKey
          FRONTEND_URL: !Ref FrontendURL
          CLOUDINARY_CLOUD_NAME: !Ref CloudinaryCloudName
          CLOUDINARY_API_KEY: !Ref CloudinaryAPIKey
          CLOUDINARY_API_SECRET: !Ref CloudinaryAPISecret
          AWS_LAMBDA_NODEJS_DISABLE_CALLBACK_WARNING: true
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref HackOverflowRestApi
            Path: /{proxy+}
            Method: ANY
        RootEvent:
          Type: Api
          Properties:
            RestApiId: !Ref HackOverflowRestApi
            Path: /
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: nodejs20.x-v1

Outputs:
  ApiUrl:
    Description: "REST API Gateway endpoint URL for prod stage"
    Value: !Sub "https://${HackOverflowRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  ApiId:
    Description: "API Gateway ID"
    Value: !Ref HackOverflowRestApi