AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HackOverflow Backend API

Parameters:
  DatabaseURL:
    Type: String
    Description: Database connection URL
    NoEcho: true
  SecretKey:
    Type: String
    Description: JWT secret key
    NoEcho: true
  FrontendURL:
    Type: String
    Description: Frontend URL for CORS
    Default: "https://your-frontend-domain.com"

Resources:
  # HTTP API Gateway with explicit stage configuration
  HackOverflowHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - !Ref FrontendURL
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Amz-Date
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowCredentials: true

  HackOverflowAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambda.handler
      Runtime: nodejs20.x
      Architectures: [arm64]
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          NODE_ENV: production
          DATABASE_URL: !Ref DatabaseURL
          SECRET_KEY: !Ref SecretKey
          FRONTEND_URL: !Ref FrontendURL
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HackOverflowHttpApi
            Path: /{proxy+}
            Method: ANY
        RootEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HackOverflowHttpApi
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Description: "HTTP API Gateway endpoint URL for prod stage"
    Value: !Sub "https://${HackOverflowHttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  ApiId:
    Description: "API Gateway ID"
    Value: !Ref HackOverflowHttpApi